services:
  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix
    restart: unless-stopped
    ports:
      - 6006:6006
      - 4317:4317
      - 4318:4318
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - ./phoenix_data:/mnt/data
    networks:
      - test_network

networks:
  test_network:
    external: true
